/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class t0mm13b_dmesglog_jni_DmesgWrapper */

#ifndef _Included_t0mm13b_dmesglog_jni_DmesgWrapper
#define _Included_t0mm13b_dmesglog_jni_DmesgWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     t0mm13b_dmesglog_jni_DmesgWrapper
 * Method:    dmesg
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_t0mm13b_dmesglog_jni_DmesgWrapper_dmesg
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
